import React from "react";
import Read from "../Read";
import '../Books.css';
import baki from "../BookImg/baki.jpeg"
import block from '../BookImg/block.jpeg';
import boruto from '../BookImg/boruto.jpeg';
import demon from '../BookImg/demon.jpeg';
import dn from '../BookImg/dn.jpeg';
import jjk from '../BookImg/jjk.jpeg';
import misfit from '../BookImg/misfit.jpeg';
import naruto from '../BookImg/naruto.jpeg';
import onep from '../BookImg/onep.jpeg';
import ttime from '../BookImg/ttime.jpeg';
import vin from '../BookImg/vin.jpeg';
import spy from '../BookImg/spy.jpeg';

const books = [
    { name: "Baki", img: baki, description: "After being poisoned by the death row convict Yanagi, Baki Hanma has been reduced to an emaciated husk. He can barely stand, much less fight. But fight he must. The Great Raitai Tournament, an ancient Chinese Martial Arts contest, is set to begin, and Baki has received an invitation. Baki cannot simply refuse. After all, among the tournament's roster is Muhammad Alai Jr., son of the greatest boxer to ever live, and Baki's own father, Yujiro Hanma, the strongest man in the world who Baki has sworn to beat in combat. At the head of the tournament are the Sea Kings; an order of Martial Artists who embody the ancient tenets of Chinese fighting. Foremost among them is Sea King Kaku, the champion of the arena who has yet to bested, even at 146 years old. Will Baki recover from his ailment and survive? And who will triumph? Will the raw power of Yujiro Hanma slam its fist and obliterate the arena? Or will a thousand years of Martial Arts tradition stand strong and prevail?v" },
    { name: "BlueLock", img: block, description: "After reflecting on the current state of Japanese soccer, the Japanese Football Association decides to hire the enigmatic and eccentric coach Jinpachi Ego to achieve their dream of winning the World Cup. Believing that Japan has lacked an egoistic striker hungry for goals, Jinpachi initiates the Blue Lock—a prison-like facility where three hundred talented strikers from high schools all over Japan are isolated and pitted against each other. The sole survivor of Blue Lock will earn the right to become the national teams striker, and those who are defeated shall be banned from joining the team forever.. Selected to join this risky project is Yoichi Isagi, a striker who failed to bring his high school soccer team to the national tournament. After choosing to pass to a teammate who missed instead of scoring on his own, he could not help but wonder if the results would have been different had he been more selfish. Using this golden opportunity given by the Blue Lock Project, Yoichi aims to clear his doubts and chase his ultimate desire—to become the greatest striker in the world and lead Japan to World Cup glory." },
    { name: "Boruto", img: boruto, description: "The Hidden Leaf Village has entered an era of peace and modernization. Skyscrapers line the streets, videos play on giant screens, and a network of trains runs through the village. Though still a ninja village, more civilians than ever roam its streets, and the shinobi must evolve with the times. While Naruto Uzumaki leads the village as the Seventh Hokage, his son Boruto begins his own journey at the Ninja Academy. Boruto's classmates only see him as the Hokage's son, but his wild and unpredictable personality quickly blows that perception away! With new friends by his side, how will Boruto handle the mysterious incidents occurring around him? A new wind is blowing, stirring up hearts as it goes. The story of Boruto Uzumaki begins now!" },
    { name: "Demon", img: demon, description: "Tanjiro Kamado, our protagonist, is a youth whose family is brutally murdered by a demon. Although badly injured, his sister, Nezuko, is the sole survivor of the attack. Tanjiro rushes to town in a desperate attempt to find medical assistance for her. Along the way, she wakes and suddenly attacks him. As Nezuko attempts to kill him, an incredible swordsman appears. The man attempts to kill Tanjiro’s demon sister, but Tanjiro protects her with his life. He tries fighting the man but is utterly outclassed. He learns that the man is a member of an underground force, known as the Demon Slayer Corps. Although he loses the battle, Tanjiro gains the man’s respect through his valiant effort and is later recommended to train under the retired Water Hashira, Sakonji Urokodaki." },
    { name: "Death Note", img: dn, description: "Light is an extremely brilliant but bored high-school student. Until the strange day where he accidentally encounters the Death Note; a mysterious notebook with the power to kill anyone whose name is written inside it. With the Death Note in hand, he goes on a personal crusade and moves to kill all evil in the world and become God. He does this all in his new name, Kira, and declares himself the law and justice of the world. At first things go as he planned, and he moves toward making a 'better' world. However, things don't go as he had anticipated as the relentless 'L' works to track him down, and arrest him." },
    { name: "Jujutsu Kaisen", img: jjk, description: "A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman's school to be able to locate the demon's other body parts and thus exorcise himself. Yuji Itadori, a kind-hearted teenager, joins his school's Occult Club for fun, but discovers that its members are actual sorcerers who can manipulate the energy between beings for their own use. He hears about a cursed talisman - the finger of Sukuna, a demon - and its being targeted by other cursed beings. Yuji eats the finger to protect his friends, and ends up becoming Sukuna's host. However, Yuji discovers that he has inherited magic and is able to control this power without interference from Sukuna. He joins the Tokyo Metropolitan Magic Technical College to consumes all of Sukuna's fingers, which will enable a full exorcism to take place that will free him." },
    { name: "Demon King Academy", img: misfit, description: "After 2,000 years of countless wars and strife, the demon king Anos Voldigoad made a deal with the human hero, Kanon, to sacrifice his own life to ensure peace could flourish. Reincarnating 2,000 years later, Anos finds that royal demons now harshly rule over lower class hybrid demons in a society that values Anos's pureblood descendants over the demons who interbred with other species, such as humans and spirits. Finding that magic as a whole has begun to decline and his descendants weaker as a result of the peace he created, Anos, The Demon King From 2000 Years ago, now technically a hybrid himself, decides to reclaim his former title of Demon King Anos Voldigoad From 2000 Years Ago, but first, he must graduate from the Demon King Academy from 2000 years ago where he is labeled a total misfit." },
    { name: "Naruto", img: naruto, description: "On the day of Naruto Uzamaki's birth the village of Konoha was attacked by the 9-tailed fox demon. In order to protect the village Naruto's father the 4th hokage sacrificed his life and sealed the demon in his new born son. 13 years later Naruto graduates the ninja academy and becomes a shinobi with goal to be the hokage of the village. Joining him are rival Sasuke Uchiha who attempts to gain power to avenge his clan after they were murdered by his older brother Itachi. And Sakura Haruno who is Naruto's love interest who of course loves his rival Sasuke. But when itachi returns to the village after the chunnin exams and Sasuke proves to be powerless against him. Sasuke will fall to the villainous Orochimaru to gain power. Naruto must do everything in his power to stop his friend from loosing himself to darkness even if it means losing himself." },
    { name: "One Piece", img: onep, description: "There once lived a pirate named Gol D. Roger. He obtained wealth, fame, and power to earn the title of Pirate King. When he was captured and about to be executed, he revealed that his treasure called One Piece was hidden somewhere at the Grand Line. This made all people set out to search and uncover the One Piece treasure, but no one ever found the location of Gol D. Roger's treasure, and the Grand Line was too dangerous a place to overcome. Twenty-two years after Gol D. Roger's death, a boy named Monkey D. Luffy decided to become a pirate and search for Gol D. Roger's treasure to become the next Pirate King." },
    { name: "That Time I Got Reincarnated As Slime", img: ttime, description: "Satoru Mikami is an ordinary 37-year-old corporate worker living in Tokyo. He is almost content with his monotonous life, despite the fact that he doesn't have a girlfriend. During a casual encounter with his colleague, an assailant pops out of nowhere and stabs him. While succumbing to his injuries, a mysterious voice echoes in his mind and recites a series of commands of which he could not make sense. After regaining consciousness, Satoru discovers that he has been reincarnated as a Slime in an unfamiliar world. At the same time, he also acquires new-found skills, particularly the ability called 'Predator,' which allows him to devour anything and mimic its appearance and skills. He stumbles upon Veldora, a powerful 'Storm Dragon', who has been sealed for the last 300 years for reducing a town to ashes. Feeling sorry for him, Satoru befriends the dragon, promising to help him in destroying the seal. They decide to exchange names, Veldora bestows upon him name Rimuru, and receives name Tempest in return. Slime then consumes the dragon together with his prison in order to analyze the spell inside itself and eventually free Veldora." },
    { name: "Vinland Saga", img: vin, description: "Vinland Saga is a historical fiction manga series written and illustrated by Makoto Yukimura. The story is set in the 11 th century, during the Viking Age, and follows a young warrior named Thorfinn, who is determined to avenge his father's death at the hands of the ruthless warlord Askeladd. The story begins with Thorfinn, who is just a boy at the time, living with his father, Thors, on the remote island of Iceland. Thors is a peaceful farmer and trader, but he has a dark past as a warrior and a member of the Viking raiders. One day, a group of warriors led by Askeladd arrives on the island and Thors is forced to fight them. Despite his peaceful nature, Thors proves to be a skilled warrior and manages to defeat Askeladd's men, but is ultimately killed by Askeladd himself. Thorfinn, who witnesses his father's death, swears to avenge him and sets out on a journey to find Askeladd. Along the way, he meets various characters, including a young slave girl named Canute, who becomes his friend and companion, and Bjorn, a warrior who becomes Thorfinn's mentor. As Thorfinn grows older, he becomes a skilled warrior in his own right and eventually gets his chance to face Askeladd in battle. However, he soon discovers that there is more to Askeladd than meets the eye and that he is not the simple villain he thought him to be. Askeladd is revealed to be a complex and nuanced character, with his own motivations and reasons for his actions. The story also explores themes of violence, power, and the nature of humanity. Through Thorfinn's journey, we see how war and violence can corrupt and change people, and how the quest for power can lead to tragedy. The series also delves into the historical context of the Viking Age, depicting the political and social conditions of the time, as well as the lifestyle and culture of the Vikings. Overall, Vinland Saga is a well-written and thought-provoking series that offers a fresh and nuanced take on the Viking genre. With its complex characters, historical accuracy, and thought-provoking themes, Vinland Saga is a must-watch for fans of historical fiction and action-adventure." },
    { name: "Spy X Family", img: spy, description: "Twilight is assigned possibly his hardest mission yet, Operation Strix. As part of this mission he needs to marry and have a child in order to get close to his target Donovan Desmond. He ends up adopting Anya, a telepath, and marrying Yor, an assassin, however, all of them are hiding their identities from one another. To complete his mission, 'Twilight' needs to get Anya enrolled in the prestigious Eden Academy so that she can get close to his target's son, Damian Desmond. To do that, Anya will need to become an Imperial Scholar by earning 8 Stella Stars, but the real challenge for 'Twilight' though is making sure she doesn't get 8 Tonitrus Bolts and get expelled!" }
]

const Book = ({ book }) => {
    return (
        <>
            <div className="card">
                <img src={book.img} alt="Avatar" />
                <div className="container">
                    <Read book={book} />
                </div>
            </div>
        </>

    );
}

function BookList() {
    const rows = [];
    for (let i = 0; i < books.length; i += 4) {
        const row = (
            <div className="row">
                {books.slice(i, i + 4).map((book) => (
                    <div className="column">
                        <Book book={book} />
                    </div>
                ))}
            </div>
        );
        rows.push(row);
    }
    return (
        <>{rows}</>
    );
}

export default BookList